export const FETCHING_PLACES = 'FETCHING_PLACES';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const FETCHING_PLACE_DETAILS = 'FETCHING_PLACE_DETAILS';
export const FETCH_PLACE_DETAILS_SUCCESS = 'FETCH_PLACE_DETAILS_SUCCESS';
export const FETCH_PLACE_DETAILS_FAILURE = 'FETCH_PLACE_DETAILS_FAILURE';